{
 "title": "Risposte per sezione: dottori",
 "time": { "from": "now-37d", "to": "now" },
 "templating": {
  "list": [
   { "name": "GROUP_TIME_INTERVAL", "label": "Raggruppa per", "query": "1s,1m,1h,1d,7d,14d,30d" }
  ]
 },
 "panels": [
  {
   "title": "Attributo: cortesia",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "voto" }
   ],
   "targets": [
    {
     "alias": "{{term tag_doctor_name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "tag_doctor_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "value.short",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "section:DOCTORS AND tag_attribute:courtesy",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Attributo: ascolto",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "voto" }
   ],
   "targets": [
    {
     "alias": "{{term tag_doctor_name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "tag_doctor_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "value.short",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "section:DOCTORS AND tag_attribute:listening",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Attributo: comunicazione",
   "type": "graph",
   "description": "Prima metà: trend pos x Paperino ~90%",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "voto" }
   ],
   "targets": [
    {
     "alias": "{{term tag_doctor_name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "tag_doctor_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "value.short",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "section:DOCTORS AND tag_attribute:communication",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Attributo: efficacia",
   "type": "graph",
   "description": "Prima metà: trend neg per Pluto ~90% - Seconda metà: trend pos per Pluto ~90%",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "voto" }
   ],
   "targets": [
    {
     "alias": "{{term tag_doctor_name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "tag_doctor_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "value.short",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "section:DOCTORS AND tag_attribute:effectiveness",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}