{
 "title": "Risposte per sezione: struttura",
 "time": { "from": "now-37d", "to": "now" },
 "templating": {
  "list": [
   { "name": "GROUP_TIME_INTERVAL", "label": "Raggruppa per", "query": "1s,1m,1h,1d,7d,14d,30d" }
  ]
 },
 "panels": [
  {
   "title": "Attributo: pulizia",
   "type": "graph",
   "description": "Prima metà: trend pos 80% - Seconda metà: trend neg 80%",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "#" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tag_sentiment",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "section:FACILITY AND tag_attribute:cleanliness AND NOT (section:FACILITY AND value:false)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Attributo: attrezzatura",
   "type": "graph",
   "description": "Prima metà: trend neg 80% - Seconda metà: trend pos 80%",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "#" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tag_sentiment",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "uuid.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "section:FACILITY AND tag_attribute:equipment AND NOT (section:FACILITY AND value:false)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Attributo: temperatura",
   "type": "graph",
   "description": "Tutto: trend pos 66%",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "#" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tag_sentiment",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "offset": "", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "section:FACILITY AND tag_attribute:temperature AND NOT (section:FACILITY AND value:false)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Attributo: organizzazione",
   "type": "graph",
   "description": "Prima metà: trend pos 66% - Seconda metà: trend neg 80%",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "#" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tag_sentiment",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "offset": "", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "section:FACILITY AND tag_attribute:planning AND NOT (section:FACILITY AND value:false)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Attributo: parcheggio",
   "type": "graph",
   "description": "Tutto: trend pos 66%",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "#" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tag_sentiment",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "offset": "", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "section:FACILITY AND tag_attribute:parking AND NOT (section:FACILITY AND value:false)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Voto complessivo",
   "type": "graph",
   "description": "Seconda metà: trend pos ~90%",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "voto" }
   ],
   "targets": [
    {
     "alias": "Media",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "offset": "", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "value.short",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "section:FACILITY AND tag_attribute:overall",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}