{
 "title": "Health QA",
 "tags": [ "qa" ],
 "time": { "to": "now", "from": "now-6h" },
 "panels": [
  {
   "title": "health",
   "type": "graph",
   "gridPos": { "y": 0, "h": 9, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short", "label": "#" }
   ],
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "meta": {},
       "type": "count",
       "id": "1",
       "settings": {}
      }
     ],
     "query": "name:health",
     "bucketAggs": [
      {
       "field": "http_status_code",
       "settings": { "orderBy": "_term", "order": "desc", "min_doc_count": 1, "size": "10" },
       "type": "terms",
       "id": "3",
       "fake": true
      },
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "healthcelery",
   "type": "graph",
   "gridPos": { "y": 0, "h": 9, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short", "label": "#" }
   ],
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "meta": {},
       "type": "count",
       "id": "1",
       "settings": {}
      }
     ],
     "query": "name:healthcelery",
     "bucketAggs": [
      {
       "field": "http_status_code",
       "settings": { "orderBy": "_term", "order": "desc", "min_doc_count": 1, "size": "10" },
       "type": "terms",
       "id": "3",
       "fake": true
      },
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "api/literature/20",
   "type": "graph",
   "gridPos": { "y": 9, "h": 9, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short", "label": "#" }
   ],
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "meta": {},
       "type": "count",
       "id": "1",
       "settings": {}
      }
     ],
     "query": "name:\"api/literature/20\"",
     "bucketAggs": [
      {
       "field": "http_status_code",
       "settings": { "orderBy": "_term", "order": "desc", "min_doc_count": 1, "size": "10" },
       "type": "terms",
       "id": "3",
       "fake": true
      },
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "timeField": "timestamp"
    }
   ]
  }
 ]
}