{
 "title": "Aspetto: struttura",
 "time": { "from": "now-37d", "to": "now" },
 "templating": {
  "list": [
   { "name": "GROUP_TIME_INTERVAL", "label": "Raggruppa per", "query": "1s,1m,1h,1d,7d,14d,30d" }
  ]
 },
 "panels": [
  {
   "title": "Sentiment",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Positivo",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag_topic:facility AND tag_sentiment:positive AND NOT (section:FACILITY AND value:false)",
     "timeField": "timestamp"
    },
    {
     "alias": "Negativo",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag_topic:facility AND tag_sentiment:negative AND NOT (section:FACILITY AND value:false)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Voto complessivo",
   "type": "graph",
   "description": "Seconda metà: trend pos ~90%",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Media",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "offset": "", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "value.short",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "tag_topic:facility AND tag_attribute:overall",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Attributo: pulizia",
   "type": "graph",
   "description": "Prima metà: trend pos 80% - Seconda metà: trend neg 80%",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Positivo",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag_topic:facility AND tag_sentiment:positive AND tag_attribute:cleanliness AND NOT (section:FACILITY AND value:false)",
     "timeField": "timestamp"
    },
    {
     "alias": "Negativo",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag_topic:facility AND tag_sentiment:negative AND tag_attribute:cleanliness AND NOT (section:FACILITY AND value:false)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Attributo: attrezzatura",
   "type": "graph",
   "description": "Prima metà: trend neg 80% - Seconda metà: trend pos 80%",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Positivo",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "uuid.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "tag_topic:facility AND tag_sentiment:positive AND tag_attribute:equipment AND NOT (section:FACILITY AND value:false)",
     "timeField": "timestamp"
    },
    {
     "alias": "Negativo",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag_topic:facility AND tag_sentiment:negative AND tag_attribute:equipment AND NOT (section:FACILITY AND value:false)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Attributo: temperatura",
   "type": "graph",
   "description": "Tutto: trend pos 66%",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Positivo",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "offset": "", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag_topic:facility AND tag_sentiment:positive AND tag_attribute:temperature AND NOT (section:FACILITY AND value:false)",
     "timeField": "timestamp"
    },
    {
     "alias": "Negativo",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag_topic:facility AND tag_sentiment:negative AND tag_attribute:temperature AND NOT (section:FACILITY AND value:false)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Attributo: organizzazione",
   "type": "graph",
   "description": "Prima metà: trend pos 66% - Seconda metà: trend neg 80%",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Positivo",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "offset": "", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag_topic:facility AND tag_sentiment:positive AND tag_attribute:planning AND NOT (section:FACILITY AND value:false)",
     "timeField": "timestamp"
    },
    {
     "alias": "Negativo",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag_topic:facility AND tag_sentiment:negative AND tag_attribute:planning AND NOT (section:FACILITY AND value:false)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Attributo: parcheggio",
   "type": "graph",
   "description": "Tutto: trend pos 66%",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Positivo",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "offset": "", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag_topic:facility AND tag_sentiment:positive AND tag_attribute:parking AND NOT (section:FACILITY AND value:false)",
     "timeField": "timestamp"
    },
    {
     "alias": "Negativo",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag_topic:facility AND tag_sentiment:negative AND tag_attribute:parking AND NOT (section:FACILITY AND value:false)",
     "timeField": "timestamp"
    },
    {
     "alias": "Non so",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag_topic:facility AND value:unknown AND tag_attribute:parking AND NOT (section:FACILITY AND value:false)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Attributo: comfort",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Media",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "offset": "", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "value.short",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "tag_topic:facility AND tag_attribute:comfort",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Attributo: location",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Media",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "offset": "", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "value.short",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "tag_topic:facility AND tag_attribute:location",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Attributo: rumoroso",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Positivo",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "offset": "", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag_topic:facility AND tag_sentiment:positive AND tag_attribute:noise AND NOT (section:FACILITY AND value:false)",
     "timeField": "timestamp"
    },
    {
     "alias": "Negativo",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag_topic:facility AND tag_sentiment:negative AND tag_attribute:noise AND NOT (section:FACILITY AND value:false)",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}