{
 "title": "Aspetto: assistenti",
 "time": { "from": "now-37d", "to": "now" },
 "templating": {
  "list": [
   { "name": "GROUP_TIME_INTERVAL", "label": "Raggruppa per", "query": "1s,1m,1h,1d,7d,14d,30d" }
  ]
 },
 "panels": [
  {
   "title": "Sentiment",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Positivo",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag_topic:assistants AND tag_sentiment:positive",
     "timeField": "timestamp"
    },
    {
     "alias": "Negativo",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag_topic:assistants AND tag_sentiment:negative",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Tutti gli attributi",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Media",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "value.short",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "tag_topic:assistants",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Attributo: cortesia",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Media",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "value.short",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "tag_topic:assistants AND tag_attribute:courtesy",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Attributo: ascolto",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Media",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "value.short",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "tag_topic:assistants AND tag_attribute:listening",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Attributo: pulizia",
   "type": "graph",
   "description": "Seconda metà: trend pos ~90%",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Media",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "value.short",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "tag_topic:assistants AND tag_attribute:cleanliness",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Attributo: comunicazione",
   "type": "graph",
   "description": "Prima metà: trend neg ~90% - Seconda metà: trend pos ~90%",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Media",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "value.short",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "tag_topic:assistants AND tag_attribute:communication",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}