{
 "title": "ORCID-push domain layer QA",
 "tags": [
  "orcid",
  "domain",
  "qa"
 ],
 "time": { "to": "now", "from": "now-6h" },
 "panels": [
  {
   "title": "OrcidPusher.push | Frequency",
   "type": "graph",
   "gridPos": { "y": 0, "h": 9, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short", "label": "#/10s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "exc_fqn",
       "settings": {
        "orderBy": "_term",
        "size": "10",
        "order": "desc",
        "min_doc_count": 1,
        "missing": "-"
       },
       "type": "terms",
       "id": "3",
       "fake": true
      },
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "10s", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "count",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "Exception: {{exc_fqn}}",
     "timeField": "timestamp",
     "query": "name:inspirehep.modules.orcid.domain_models.OrcidPusher.push"
    }
   ]
  },
  {
   "title": "OrcidPusher.push | Duration",
   "type": "graph",
   "gridPos": { "y": 0, "h": 9, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short", "label": "msec" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "avg",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "Duration",
     "timeField": "timestamp",
     "query": "name:inspirehep.modules.orcid.domain_models.OrcidPusher.push"
    }
   ]
  },
  {
   "title": "OrcidPusher._get_inspire_record | Frequency",
   "type": "graph",
   "gridPos": { "y": 9, "h": 9, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short", "label": "#/10s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "exc_fqn",
       "settings": {
        "orderBy": "_term",
        "size": "10",
        "order": "desc",
        "min_doc_count": 1,
        "missing": "-"
       },
       "type": "terms",
       "id": "3",
       "fake": true
      },
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "10s", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "count",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "Exception: {{exc_fqn}}",
     "timeField": "timestamp",
     "query": "name:inspirehep.modules.orcid.domain_models.OrcidPusher._get_inspire_record"
    }
   ]
  },
  {
   "title": "OrcidPusher._get_inspire_record | Duration",
   "type": "graph",
   "gridPos": { "y": 9, "h": 9, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short", "label": "msec" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "avg",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "Duration",
     "timeField": "timestamp",
     "query": "name:inspirehep.modules.orcid.domain_models.OrcidPusher._get_inspire_record"
    }
   ]
  },
  {
   "title": "OrcidPusher._post_or_put_work | Frequency",
   "type": "graph",
   "gridPos": { "y": 18, "h": 9, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short", "label": "#/10s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "exc_fqn",
       "settings": {
        "orderBy": "_term",
        "size": "10",
        "order": "desc",
        "min_doc_count": 1,
        "missing": "-"
       },
       "type": "terms",
       "id": "3",
       "fake": true
      },
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "10s", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "count",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "Exception: {{exc_fqn}}",
     "timeField": "timestamp",
     "query": "name:inspirehep.modules.orcid.domain_models.OrcidPusher._post_or_put_work"
    }
   ]
  },
  {
   "title": "OrcidPusher._post_or_put_work | Duration",
   "type": "graph",
   "gridPos": { "y": 18, "h": 9, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short", "label": "msec" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "avg",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "Duration",
     "timeField": "timestamp",
     "query": "name:inspirehep.modules.orcid.domain_models.OrcidPusher._post_or_put_work"
    }
   ]
  },
  {
   "title": "OrcidPusher._cache_all_author_putcodes | Frequency",
   "type": "graph",
   "gridPos": { "y": 27, "h": 9, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short", "label": "#/10s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "exc_fqn",
       "settings": {
        "orderBy": "_term",
        "size": "10",
        "order": "desc",
        "min_doc_count": 1,
        "missing": "-"
       },
       "type": "terms",
       "id": "3",
       "fake": true
      },
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "10s", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "count",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "Exception: {{exc_fqn}}",
     "timeField": "timestamp",
     "query": "name:inspirehep.modules.orcid.domain_models.OrcidPusher._cache_all_author_putcodes"
    }
   ]
  },
  {
   "title": "OrcidPusher._cache_all_author_putcodes | Duration",
   "type": "graph",
   "gridPos": { "y": 27, "h": 9, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short", "label": "msec" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "avg",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "Duration",
     "timeField": "timestamp",
     "query": "name:inspirehep.modules.orcid.domain_models.OrcidPusher._cache_all_author_putcodes"
    }
   ]
  },
  {
   "title": "OrcidPusher._delete_work | Frequency",
   "type": "graph",
   "gridPos": { "y": 36, "h": 9, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short", "label": "#/10s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "exc_fqn",
       "settings": {
        "orderBy": "_term",
        "size": "10",
        "order": "desc",
        "min_doc_count": 1,
        "missing": "-"
       },
       "type": "terms",
       "id": "3",
       "fake": true
      },
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "10s", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "count",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "Exception: {{exc_fqn}}",
     "timeField": "timestamp",
     "query": "name:inspirehep.modules.orcid.domain_models.OrcidPusher._delete_work"
    }
   ]
  },
  {
   "title": "OrcidPusher._delete_work | Duration",
   "type": "graph",
   "gridPos": { "y": 36, "h": 9, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short", "label": "msec" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "avg",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "Duration",
     "timeField": "timestamp",
     "query": "name:inspirehep.modules.orcid.domain_models.OrcidPusher._delete_work"
    }
   ]
  },
  {
   "title": "OrcidPusher._push_work_with_clashing_identifier | Frequency",
   "type": "graph",
   "gridPos": { "y": 45, "h": 9, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short", "label": "#/10s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "exc_fqn",
       "settings": {
        "orderBy": "_term",
        "size": "10",
        "order": "desc",
        "min_doc_count": 1,
        "missing": "-"
       },
       "type": "terms",
       "id": "3",
       "fake": true
      },
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "10s", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "count",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "Exception: {{exc_fqn}}",
     "timeField": "timestamp",
     "query": "name:inspirehep.modules.orcid.domain_models.OrcidPusher._push_work_with_clashing_identifier"
    }
   ]
  },
  {
   "title": "OrcidPusher._push_work_with_clashing_identifier | Duration",
   "type": "graph",
   "gridPos": { "y": 45, "h": 9, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short", "label": "msec" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "avg",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "Duration",
     "timeField": "timestamp",
     "query": "name:inspirehep.modules.orcid.domain_models.OrcidPusher._push_work_with_clashing_identifier"
    }
   ]
  },
  {
   "title": "OrcidConverter.* | Frequency",
   "type": "graph",
   "gridPos": { "y": 54, "h": 9, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short", "label": "#/10s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "name",
       "settings": { "orderBy": "_term", "order": "desc", "min_doc_count": 1, "size": "10" },
       "type": "terms",
       "id": "4",
       "fake": true
      },
      {
       "field": "exc_fqn",
       "settings": {
        "orderBy": "_term",
        "size": "10",
        "order": "desc",
        "min_doc_count": 1,
        "missing": "-"
       },
       "type": "terms",
       "id": "3",
       "fake": true
      },
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "10s", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "count",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "{{name}} | exception: {{exc_fqn}}",
     "timeField": "timestamp",
     "query": "name:inspirehep.modules.orcid.converter.*"
    }
   ]
  },
  {
   "title": "OrcidConverter.* | Duration",
   "type": "graph",
   "gridPos": { "y": 54, "h": 9, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short", "label": "msec" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "name",
       "settings": { "orderBy": "_term", "order": "desc", "min_doc_count": 1, "size": "10" },
       "type": "terms",
       "id": "3",
       "fake": true
      },
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "avg",
       "id": "1",
       "settings": {}
      }
     ],
     "timeField": "timestamp",
     "query": "name:inspirehep.modules.orcid.converter.*"
    }
   ]
  },
  {
   "title": "delete_access_token | Frequency",
   "type": "graph",
   "gridPos": { "y": 63, "h": 9, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short", "label": "#/10s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "exc_fqn",
       "settings": {
        "orderBy": "_term",
        "size": "10",
        "order": "desc",
        "min_doc_count": 1,
        "missing": "-"
       },
       "type": "terms",
       "id": "3",
       "fake": true
      },
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "10s", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "count",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "Exception: {{exc_fqn}}",
     "timeField": "timestamp",
     "query": "name:inspirehep.modules.orcid.push_access_tokens.delete_access_token"
    }
   ]
  },
  {
   "title": "delete_access_token | Duration",
   "type": "graph",
   "gridPos": { "y": 63, "h": 9, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short", "label": "msec" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "avg",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "Duration",
     "timeField": "timestamp",
     "query": "name:inspirehep.modules.orcid.push_access_tokens.delete_access_token"
    }
   ]
  },
  {
   "title": "OrcidCache.* | Frequency",
   "type": "graph",
   "gridPos": { "y": 72, "h": 9, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short", "label": "#/10s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "name",
       "settings": { "orderBy": "_term", "order": "desc", "min_doc_count": 1, "size": "10" },
       "type": "terms",
       "id": "4",
       "fake": true
      },
      {
       "field": "exc_fqn",
       "settings": {
        "orderBy": "_term",
        "size": "10",
        "order": "desc",
        "min_doc_count": 1,
        "missing": "-"
       },
       "type": "terms",
       "id": "3",
       "fake": true
      },
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "10s", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "count",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "{{name}} | exception: {{exc_fqn}}",
     "timeField": "timestamp",
     "query": "name:inspirehep.modules.orcid.cache.OrcidCache.*"
    }
   ]
  },
  {
   "title": "OrcidCache.* | Duration",
   "type": "graph",
   "gridPos": { "y": 72, "h": 9, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short", "label": "msec" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "name",
       "settings": { "orderBy": "_term", "order": "desc", "min_doc_count": 1, "size": "10" },
       "type": "terms",
       "id": "3",
       "fake": true
      },
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "avg",
       "id": "1",
       "settings": {}
      }
     ],
     "timeField": "timestamp",
     "query": "name:inspirehep.modules.orcid.cache.OrcidCache.*"
    }
   ]
  },
  {
   "title": "OrcidCache | Frequency",
   "type": "graph",
   "gridPos": { "y": 81, "h": 9, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short", "label": "#/10s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "count",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "Cache hit",
     "timeField": "@timestamp",
     "query": "message:\"inspirehep.modules.orcid.domain_models: OrcidPusher cache hit*\""
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "metrics": [
      { "field": "select field", "type": "count", "id": "1" }
     ],
     "alias": "Cache miss",
     "timeField": "@timestamp",
     "query": "message:\"inspirehep.modules.orcid.domain_models: OrcidPusher cache miss*\""
    }
   ]
  }
 ]
}