{
 "title": "Health",
 "time": { "to": "now", "from": "now-6h" },
 "panels": [
  {
   "title": "health",
   "type": "graph",
   "gridPos": { "y": 0, "h": 9, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short", "label": "#" }
   ],
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "meta": {},
       "type": "count",
       "id": "1",
       "settings": {}
      }
     ],
     "query": "name:health",
     "bucketAggs": [
      {
       "field": "http_status_code",
       "settings": { "orderBy": "_term", "order": "desc", "min_doc_count": 1, "size": "10" },
       "type": "terms",
       "id": "3",
       "fake": true
      },
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "healthcelery",
   "type": "graph",
   "gridPos": { "y": 0, "h": 9, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short", "label": "#" }
   ],
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "meta": {},
       "type": "count",
       "id": "1",
       "settings": {}
      }
     ],
     "query": "name:healthcelery",
     "bucketAggs": [
      {
       "field": "http_status_code",
       "settings": { "orderBy": "_term", "order": "desc", "min_doc_count": 1, "size": "10" },
       "type": "terms",
       "id": "3",
       "fake": true
      },
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "api/literature/20",
   "type": "graph",
   "gridPos": { "y": 9, "h": 9, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short", "label": "#" }
   ],
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "meta": {},
       "type": "count",
       "id": "1",
       "settings": {}
      }
     ],
     "query": "name:\"api/literature/20\"",
     "bucketAggs": [
      {
       "field": "http_status_code",
       "settings": { "orderBy": "_term", "order": "desc", "min_doc_count": 1, "size": "10" },
       "type": "terms",
       "id": "3",
       "fake": true
      },
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "time-execution errors",
   "type": "graph",
   "gridPos": { "y": 9, "h": 9, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short", "label": "#" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "host.keyword",
       "settings": { "orderBy": "_term", "order": "desc", "min_doc_count": 1, "size": "10" },
       "type": "terms",
       "id": "3",
       "fake": true
      },
      { "field": "@timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "select field",
       "meta": {},
       "type": "count",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "Queue full on {{host.keyword}}",
     "timeField": "@timestamp",
     "query": "message:\"Discard metric\""
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "metrics": [
      { "field": "select field", "type": "count", "id": "1" }
     ],
     "alias": "Write error",
     "timeField": "@timestamp",
     "query": "message:\"write failure\""
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "metrics": [
      { "field": "select field", "type": "count", "id": "1" }
     ],
     "alias": "Worker stopped",
     "timeField": "@timestamp",
     "query": "message:\"stopping the worker due to\""
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "metrics": [
      { "field": "select field", "type": "count", "id": "1" }
     ],
     "alias": "ES TransportError (like ConnectionTimeout)",
     "timeField": "@timestamp",
     "query": "message:\"bulk_write metrics\""
    }
   ]
  }
 ]
}