{
 "title": "ORCID-push infra",
 "tags": [
  "orcid",
  "infra"
 ],
 "time": { "to": "now", "from": "now-2d" },
 "templating": {
  "list": [
   {
    "name": "HOST",
    "query": "{\"find\": \"terms\", \"field\": \"host.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "RabbitMQ (from Jenkins inspire-orcidpush-monitoring)",
   "type": "graph",
   "gridPos": { "y": 0, "h": 9, "w": 24, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "5m", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "count",
       "meta": {},
       "type": "avg",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "consumers",
     "timeField": "timestamp",
     "query": "name:rabbit-queue-orcid_push-counsumers-count"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "5m", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "count",
       "meta": {},
       "type": "avg",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "messages",
     "timeField": "timestamp",
     "query": "name:rabbit-queue-orcid_push-messages-count"
    }
   ]
  },
  {
   "title": "Flower (from Jenkins inspire-orcidpush-monitoring)",
   "type": "graph",
   "gridPos": { "y": 9, "h": 9, "w": 24, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metrics": [
      {
       "field": "count",
       "meta": {},
       "type": "avg",
       "id": "1",
       "settings": {}
      }
     ],
     "query": "name:inspirehep.modules.orcid.tasks.orcid_push",
     "bucketAggs": [
      {
       "field": "state",
       "settings": { "orderBy": "_term", "order": "desc", "min_doc_count": 1, "size": "0" },
       "type": "terms",
       "id": "3",
       "fake": true
      },
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "5m", "min_doc_count": 0 } }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Celery (from Celery log file)",
   "type": "graph",
   "description": "# received = # succeeded + # retry + # error\n\nThat's because Celery logs are like:\n1) in case of success:\n- received\n- succeeded\n2) in case of error:\n- received\n   - received\n   - retry (1st retry attempt)\n   - received\n   - retry (2nd retry attempt)\n   - received\n   - retry (3rd retry attempt)\n- error",
   "gridPos": { "y": 18, "h": 9, "w": 24, "x": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "metrics": [
      { "field": "select field", "type": "count", "id": "1" }
     ],
     "alias": "RECEIVED",
     "timeField": "@timestamp",
     "query": "tags:worker AND message:\"Received task: inspirehep.modules.orcid.tasks.orcid_push\" AND host:\"$HOST\""
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "metrics": [
      { "field": "select field", "type": "count", "id": "1" }
     ],
     "alias": "SUCCEEDED",
     "timeField": "@timestamp",
     "query": "tags:worker AND message:\"succeeded\" AND message:\"inspirehep.modules.orcid.tasks.orcid_push\" AND host:\"$HOST\""
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "metrics": [
      { "field": "select field", "type": "count", "id": "1" }
     ],
     "alias": "RETRY",
     "timeField": "@timestamp",
     "query": "tags:worker AND message:\"retry: Retry in 300s\" AND message:\"inspirehep.modules.orcid.tasks.orcid_push\" AND host:\"$HOST\""
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "metrics": [
      { "field": "select field", "type": "count", "id": "1" }
     ],
     "alias": "ERROR",
     "timeField": "@timestamp",
     "query": "tags:worker AND message:\"ERROR/ForkPoolWorker\" AND message:\"inspirehep.modules.orcid.tasks.orcid_push\" AND message:\"raised unexpected\"  AND host:\"$HOST\""
    }
   ]
  }
 ]
}