{
 "title": "ORCID-push service layer",
 "tags": [
  "orcid",
  "service"
 ],
 "time": { "to": "now", "from": "now-6h" },
 "panels": [
  {
   "title": "* | Frequency",
   "type": "graph",
   "gridPos": { "y": 0, "h": 9, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short", "label": "#/10s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "http_status_code",
       "settings": { "orderBy": "_term", "order": "desc", "min_doc_count": 1, "size": "10" },
       "type": "terms",
       "id": "7",
       "fake": true
      },
      {
       "field": "orcid_service_exc",
       "settings": {
        "orderBy": "_term",
        "size": "10",
        "order": "desc",
        "min_doc_count": 1,
        "missing": "-"
       },
       "type": "terms",
       "id": "8",
       "fake": true
      },
      {
       "field": "orcid_error_code",
       "settings": {
        "orderBy": "_term",
        "size": "10",
        "order": "desc",
        "min_doc_count": 1,
        "missing": "0"
       },
       "type": "terms",
       "id": "6",
       "fake": true
      },
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "10s", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "count",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "HTTP STATUS {{term http_status_code}} | {{term orcid_service_exc}} error: {{term orcid_error_code}}",
     "timeField": "timestamp",
     "query": "name:inspire_service_orcid.client.OrcidClient.*"
    }
   ]
  },
  {
   "title": "* | Duration",
   "type": "graph",
   "gridPos": { "y": 0, "h": 9, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short", "label": "msec" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "http_status_code",
       "settings": { "orderBy": "_term", "order": "desc", "min_doc_count": 1, "size": "10" },
       "type": "terms",
       "id": "5",
       "fake": true
      },
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "avg",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "HTTP STATUS {{term http_status_code}}",
     "timeField": "timestamp",
     "query": "name:inspire_service_orcid.client.OrcidClient.*"
    }
   ]
  },
  {
   "title": "PUT put_updated_work | Frequency",
   "type": "graph",
   "gridPos": { "y": 9, "h": 9, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short", "label": "#/10s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "http_status_code",
       "settings": { "orderBy": "_term", "order": "desc", "min_doc_count": 1, "size": "10" },
       "type": "terms",
       "id": "5",
       "fake": true
      },
      {
       "field": "orcid_service_exc",
       "settings": {
        "orderBy": "_term",
        "size": "10",
        "order": "desc",
        "min_doc_count": 1,
        "missing": "-"
       },
       "type": "terms",
       "id": "6",
       "fake": true
      },
      {
       "field": "orcid_error_code",
       "settings": {
        "orderBy": "_term",
        "size": "10",
        "order": "desc",
        "min_doc_count": 1,
        "missing": "0"
       },
       "type": "terms",
       "id": "4",
       "fake": true
      },
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "10s", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "count",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "HTTP STATUS {{term http_status_code}} | {{term orcid_service_exc}} error: {{term orcid_error_code}}",
     "timeField": "timestamp",
     "query": "name:inspire_service_orcid.client.OrcidClient.put_updated_work"
    }
   ]
  },
  {
   "title": "PUT put_updated_work | Duration",
   "type": "graph",
   "gridPos": { "y": 9, "h": 9, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short", "label": "msec" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "http_status_code",
       "settings": { "orderBy": "_term", "order": "desc", "min_doc_count": 1, "size": "10" },
       "type": "terms",
       "id": "5",
       "fake": true
      },
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "avg",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "HTTP STATUS {{term http_status_code}}",
     "timeField": "timestamp",
     "query": "name:inspire_service_orcid.client.OrcidClient.put_updated_work"
    }
   ]
  },
  {
   "title": "POST post_new_work | Frequency",
   "type": "graph",
   "gridPos": { "y": 18, "h": 9, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short", "label": "#/10s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "http_status_code",
       "settings": { "orderBy": "_term", "order": "desc", "min_doc_count": 1, "size": "10" },
       "type": "terms",
       "id": "5",
       "fake": true
      },
      {
       "field": "orcid_service_exc",
       "settings": {
        "orderBy": "_term",
        "size": "10",
        "order": "desc",
        "min_doc_count": 1,
        "missing": "-"
       },
       "type": "terms",
       "id": "6",
       "fake": true
      },
      {
       "field": "orcid_error_code",
       "settings": {
        "orderBy": "_term",
        "size": "10",
        "order": "desc",
        "min_doc_count": 1,
        "missing": "0"
       },
       "type": "terms",
       "id": "4",
       "fake": true
      },
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "10s", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "count",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "HTTP STATUS {{term http_status_code}} | {{term orcid_service_exc}} error: {{term orcid_error_code}}",
     "timeField": "timestamp",
     "query": "name:inspire_service_orcid.client.OrcidClient.post_new_work"
    }
   ]
  },
  {
   "title": "POST post_new_work | Duration",
   "type": "graph",
   "gridPos": { "y": 18, "h": 9, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short", "label": "msec" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "http_status_code",
       "settings": { "orderBy": "_term", "order": "desc", "min_doc_count": 1, "size": "10" },
       "type": "terms",
       "id": "5",
       "fake": true
      },
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "avg",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "HTTP STATUS {{term http_status_code}}",
     "timeField": "timestamp",
     "query": "name:inspire_service_orcid.client.OrcidClient.post_new_work"
    }
   ]
  },
  {
   "title": "GET _get_bulk_works_details | Frequency",
   "type": "graph",
   "gridPos": { "y": 27, "h": 9, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short", "label": "#/10s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "http_status_code",
       "settings": { "orderBy": "_term", "order": "desc", "min_doc_count": 1, "size": "10" },
       "type": "terms",
       "id": "5",
       "fake": true
      },
      {
       "field": "orcid_service_exc",
       "settings": {
        "orderBy": "_term",
        "size": "10",
        "order": "desc",
        "min_doc_count": 1,
        "missing": "-"
       },
       "type": "terms",
       "id": "6",
       "fake": true
      },
      {
       "field": "orcid_error_code",
       "settings": {
        "orderBy": "_term",
        "size": "10",
        "order": "desc",
        "min_doc_count": 1,
        "missing": "0"
       },
       "type": "terms",
       "id": "4",
       "fake": true
      },
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "10s", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "count",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "HTTP STATUS {{term http_status_code}} | {{term orcid_service_exc}} error: {{term orcid_error_code}}",
     "timeField": "timestamp",
     "query": "name:inspire_service_orcid.client.OrcidClient._get_bulk_works_details"
    }
   ]
  },
  {
   "title": "GET _get_bulk_works_details | Duration",
   "type": "graph",
   "gridPos": { "y": 27, "h": 9, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short", "label": "msec" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "http_status_code",
       "settings": { "orderBy": "_term", "order": "desc", "min_doc_count": 1, "size": "10" },
       "type": "terms",
       "id": "5",
       "fake": true
      },
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "avg",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "HTTP STATUS {{term http_status_code}}",
     "timeField": "timestamp",
     "query": "name:inspire_service_orcid.client.OrcidClient._get_bulk_works_details"
    }
   ]
  },
  {
   "title": "GET get_all_works_summary | Frequency",
   "type": "graph",
   "gridPos": { "y": 36, "h": 9, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short", "label": "#/10s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "http_status_code",
       "settings": { "orderBy": "_term", "order": "desc", "min_doc_count": 1, "size": "10" },
       "type": "terms",
       "id": "5",
       "fake": true
      },
      {
       "field": "orcid_service_exc",
       "settings": {
        "orderBy": "_term",
        "size": "10",
        "order": "desc",
        "min_doc_count": 1,
        "missing": "-"
       },
       "type": "terms",
       "id": "6",
       "fake": true
      },
      {
       "field": "orcid_error_code",
       "settings": {
        "orderBy": "_term",
        "size": "10",
        "order": "desc",
        "min_doc_count": 1,
        "missing": "0"
       },
       "type": "terms",
       "id": "4",
       "fake": true
      },
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "10s", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "count",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "HTTP STATUS {{term http_status_code}} | {{term orcid_service_exc}} error: {{term orcid_error_code}}",
     "timeField": "timestamp",
     "query": "name:inspire_service_orcid.client.OrcidClient.get_all_works_summary"
    }
   ]
  },
  {
   "title": "GET get_all_works_summary | Duration",
   "type": "graph",
   "gridPos": { "y": 36, "h": 9, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short", "label": "msec" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "http_status_code",
       "settings": { "orderBy": "_term", "order": "desc", "min_doc_count": 1, "size": "10" },
       "type": "terms",
       "id": "5",
       "fake": true
      },
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "avg",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "HTTP STATUS {{term http_status_code}}",
     "timeField": "timestamp",
     "query": "name:inspire_service_orcid.client.OrcidClient.get_all_works_summary"
    }
   ]
  }
 ]
}