{
 "title": "ORCID-push tasks layer QA",
 "tags": [
  "orcid",
  "tasks",
  "qa"
 ],
 "time": { "to": "now", "from": "now-6h" },
 "panels": [
  {
   "title": "Task import_legacy_orcid_tokens | Frequency",
   "type": "graph",
   "gridPos": { "y": 0, "h": 9, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short", "label": "#/10s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "exc_fqn",
       "settings": {
        "orderBy": "_term",
        "size": "10",
        "order": "desc",
        "min_doc_count": 1,
        "missing": "-"
       },
       "type": "terms",
       "id": "3",
       "fake": true
      },
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "10s", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "count",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "Exception: {{exc_fqn}}",
     "timeField": "timestamp",
     "query": "name:inspirehep.modules.orcid.tasks.import_legacy_orcid_tokens.import_legacy_orcid_tokens"
    }
   ]
  },
  {
   "title": "Task import_legacy_orcid_tokens | Duration",
   "type": "graph",
   "gridPos": { "y": 0, "h": 9, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short", "label": "msec" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "avg",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "Duration",
     "timeField": "timestamp",
     "query": "name:inspirehep.modules.orcid.tasks.import_legacy_orcid_tokens.*"
    }
   ]
  },
  {
   "title": "Task orcid_push | Frequency",
   "type": "graph",
   "gridPos": { "y": 9, "h": 9, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short", "label": "#/10s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "exc_fqn",
       "settings": {
        "orderBy": "_term",
        "size": "10",
        "order": "desc",
        "min_doc_count": 1,
        "missing": "-"
       },
       "type": "terms",
       "id": "3",
       "fake": true
      },
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "10s", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "count",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "Exception: {{exc_fqn}}",
     "timeField": "timestamp",
     "query": "name:inspirehep.modules.orcid.tasks.orcid_push.orcid_push"
    }
   ]
  },
  {
   "title": "Task orcid_push | Duration",
   "type": "graph",
   "gridPos": { "y": 9, "h": 9, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short", "label": "msec" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "avg",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "Duration",
     "timeField": "timestamp",
     "query": "name:inspirehep.modules.orcid.tasks.orcid_push.orcid_push"
    }
   ]
  },
  {
   "title": "Receiver push_to_orcid | Frequency",
   "type": "graph",
   "gridPos": { "y": 18, "h": 9, "w": 12, "x": 0 },
   "yaxes": [
    { "format": "short", "label": "#/10s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "exc_fqn",
       "settings": {
        "orderBy": "_term",
        "size": "10",
        "order": "desc",
        "min_doc_count": 1,
        "missing": "-"
       },
       "type": "terms",
       "id": "3",
       "fake": true
      },
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "10s", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "count",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "Exception: {{exc_fqn}}",
     "timeField": "timestamp",
     "query": "name:inspirehep.modules.records.receivers.push_to_orcid"
    }
   ]
  },
  {
   "title": "Receiver push_to_orcid | Duration",
   "type": "graph",
   "gridPos": { "y": 18, "h": 9, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short", "label": "msec" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "type": "date_histogram", "id": "2", "settings": { "trimEdges": 0, "interval": "auto", "min_doc_count": 0 } }
     ],
     "metrics": [
      {
       "field": "value",
       "meta": {},
       "type": "avg",
       "id": "1",
       "settings": {}
      }
     ],
     "alias": "Duration",
     "timeField": "timestamp",
     "query": "name:inspirehep.modules.records.receivers.push_to_orcid"
    }
   ]
  }
 ]
}