{
 "title": "Risposte per sezione: domande brevi",
 "time": { "from": "2019-12-31T22:02:09.433Z", "to": "2020-01-30T16:42:16.497Z" },
 "templating": {
  "list": [
   { "name": "GROUP_TIME_INTERVAL", "label": "Raggruppa per", "query": "1s,1m,1h,1d,7d,14d,30d" }
  ]
 },
 "panels": [
  {
   "title": "Quanti assistenti alla poltrona hai visto nello studio?",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "1- o 2 o 3+" }
   ],
   "targets": [
    {
     "alias": "Media",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "value.short",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "section:RANDOM AND uuid:rqgvyba",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Lo studio è confortevole?",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "voto" }
   ],
   "targets": [
    {
     "alias": "Media",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "value.short",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "section:RANDOM AND uuid:rqtjikb",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Accetta pagamenti rateizzati?",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "#" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "value",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "2",
       "settings": {
        "interval": "auto",
        "min_doc_count": 1,
        "offset": "",
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "section:RANDOM AND uuid:rq1b3lc",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Quante settimane devi attendere per un appuntamento?",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "1- o 2 o 3+" }
   ],
   "targets": [
    {
     "alias": "Media",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "value.short",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "section:RANDOM AND uuid:rq8k21d",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Gli ambulatori sono puliti?",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "voto" }
   ],
   "targets": [
    {
     "alias": "Media",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "value.short",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "section:RANDOM AND uuid:rqd3sne",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "C'è parcheggio libero nelle vicinanze?",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "#" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "value",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 1, "offset": "", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "section:RANDOM AND uuid:rquaqkf",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "È presente una segretaria?",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "#" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "value",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 1, "offset": "", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "section:RANDOM AND uuid:rqi8jbg",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "I servizi igienici sono puliti?",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "voto" }
   ],
   "targets": [
    {
     "alias": "Media",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "value.short",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "section:RANDOM AND uuid:rq6lg3h",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Lo studio è facilmente raggiungibile?",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "voto" }
   ],
   "targets": [
    {
     "alias": "Media",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "$GROUP_TIME_INTERVAL", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "value.short",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "section:RANDOM AND uuid:rqo2oci",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Gli ambulatori sono troppo rumorosi?",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "#" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "value",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 1, "offset": "", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "section:RANDOM AND uuid:rqiyoxl",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}